#!/bin/sh

data_dir="$(dirname "$0")/data"
data_file="$data_dir/spotify-art"
data_img="$HOME/Pictures/npart.jpg"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

touch "$data_file"

test="$(playerctl -p spotify metadata mpris:artUrl)"

url="$(echo "$test" | sed 's;https://open.spotify.com;http://i.scdn.co;g')"
content="$(cat "$data_file")"

if [ "$content" != "$url" ]; then
    echo "$url" > "$data_file"
    curl -s "$url" > "$data_img"
fi
