#!/bin/sh

data_dir="$(dirname "$0")/../data"
data_file="$data_dir/cmus-art"
data_img="$data_dir/cmus.jpg"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

touch "$data_file"


url="$(cmus-remote -Q 2>/dev/null | grep 'file' | cut -d " " -f 2-)"
content="$(cat "$data_file")"

if [ -n "$url" ] && [ "$content" != "$url" ]; then
    echo "$url" > "$data_file"
    ffmpeg -y -i "$url" -an -vcodec copy "$data_img"
fi
