#!/bin/sh

data_dir="$(dirname "$0")/../data"
data_file="$data_dir/spotify-art"
data_img="$data_dir/spotify.jpg"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

touch "$data_file"

url="$(playerctl -p spotify metadata mpris:artUrl | sed 's;https://open.spotify.com;http://i.scdn.co;g')"
content="$(cat "$data_file")"

if [ -n "$url" ] && [ "$content" != "$url" ]; then
    echo "$url" > "$data_file"
    curl -s "$url" > "$data_img"
fi
